packaging_format = 2

id = "chitchatter"
name = "Chitchatter"
description.en = "Peer-to-peer chat that is serverless, decentralized, and ephemeral"
description.fr = "Chat peer-to-peer sans serveur, décentralisée et éphémère"

version = "2026.06.04~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0"
website = "https://chitchatter.im/"
demo = "https://chitchatter.im/"
code = "https://github.com/jeremyckahn/chitchatter"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "1500M"
ram.build = "2800M"
ram.runtime = "250M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    # for update notification only.
    [resources.sources.main]
    url = "https://github.com/jeremyckahn/chitchatter/archive/76e4ec08c53ec55e59d6ab154804af64591558bf.tar.gz"
    sha256 = "22a5e71d55ad783eca49f46a08722375df4db579fc6c45e0f1b223d2ff26bb55"
    autoupdate.upstream = "https://github.com/jeremyckahn/chitchatter"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    
    [resources.nodejs]
    version = "22"
