packaging_format = 2

id = "chitchatter"
name = "Chitchatter"
description.en = "Peer-to-peer chat that is serverless, decentralized, and ephemeral"
description.fr = "Chat peer-to-peer sans serveur, décentralisée et éphémère"

version = "2026.05.27~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0"
website = "https://chitchatter.im/"
demo = "https://chitchatter.im/"
code = "https://github.com/jeremyckahn/chitchatter"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "1500M"
ram.build = "2800M"
ram.runtime = "250M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    # for update notification only.
    [resources.sources.main]
    url = "https://github.com/jeremyckahn/chitchatter/archive/3adbd1d57c63c94786c0194a44a6434b450f87a8.tar.gz"
    sha256 = "52a46f6e0d84b7251ee7ec9493fd5d286af75ee1ae9581d39cc8bae96ec0b757"
    autoupdate.upstream = "https://github.com/jeremyckahn/chitchatter"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    
    [resources.nodejs]
    version = "22"
